# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ledger.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ledger.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cledger.proto\x12\x06ledger\"C\n\rLedgerRequest\x12\x12\n\npayment_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x02\x12\x0e\n\x06method\x18\x03 \x01(\t\"I\n\x13RefundLedgerRequest\x12\x12\n\npayment_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x02\x12\x0e\n\x06method\x18\x03 \x01(\t\"\'\n\x14RefundLedgerResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"!\n\x0eLedgerResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\x9e\x01\n\rLedgerService\x12\x42\n\x11RecordTransaction\x12\x15.ledger.LedgerRequest\x1a\x16.ledger.LedgerResponse\x12I\n\x0cRecordRefund\x12\x1b.ledger.RefundLedgerRequest\x1a\x1c.ledger.RefundLedgerResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ledger_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LEDGERREQUEST']._serialized_start=24
  _globals['_LEDGERREQUEST']._serialized_end=91
  _globals['_REFUNDLEDGERREQUEST']._serialized_start=93
  _globals['_REFUNDLEDGERREQUEST']._serialized_end=166
  _globals['_REFUNDLEDGERRESPONSE']._serialized_start=168
  _globals['_REFUNDLEDGERRESPONSE']._serialized_end=207
  _globals['_LEDGERRESPONSE']._serialized_start=209
  _globals['_LEDGERRESPONSE']._serialized_end=242
  _globals['_LEDGERSERVICE']._serialized_start=245
  _globals['_LEDGERSERVICE']._serialized_end=403
# @@protoc_insertion_point(module_scope)
