# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ledger_pb2 as ledger__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ledger_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LedgerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RecordTransaction = channel.unary_unary(
                '/ledger.LedgerService/RecordTransaction',
                request_serializer=ledger__pb2.LedgerRequest.SerializeToString,
                response_deserializer=ledger__pb2.LedgerResponse.FromString,
                _registered_method=True)
        self.RecordRefund = channel.unary_unary(
                '/ledger.LedgerService/RecordRefund',
                request_serializer=ledger__pb2.RefundLedgerRequest.SerializeToString,
                response_deserializer=ledger__pb2.RefundLedgerResponse.FromString,
                _registered_method=True)


class LedgerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RecordTransaction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecordRefund(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LedgerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RecordTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordTransaction,
                    request_deserializer=ledger__pb2.LedgerRequest.FromString,
                    response_serializer=ledger__pb2.LedgerResponse.SerializeToString,
            ),
            'RecordRefund': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordRefund,
                    request_deserializer=ledger__pb2.RefundLedgerRequest.FromString,
                    response_serializer=ledger__pb2.RefundLedgerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ledger.LedgerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ledger.LedgerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LedgerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RecordTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ledger.LedgerService/RecordTransaction',
            ledger__pb2.LedgerRequest.SerializeToString,
            ledger__pb2.LedgerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecordRefund(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ledger.LedgerService/RecordRefund',
            ledger__pb2.RefundLedgerRequest.SerializeToString,
            ledger__pb2.RefundLedgerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
