# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import generated_pb2.refund_pb2 as refund__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in refund_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RefundServiceStub(object):
    """Service Message 
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateRefund = channel.unary_unary(
                '/refund.RefundService/CreateRefund',
                request_serializer=refund__pb2.RefundRequest.SerializeToString,
                response_deserializer=refund__pb2.RefundResponse.FromString,
                _registered_method=True)


class RefundServiceServicer(object):
    """Service Message 
    """

    def CreateRefund(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RefundServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateRefund': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateRefund,
                    request_deserializer=refund__pb2.RefundRequest.FromString,
                    response_serializer=refund__pb2.RefundResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'refund.RefundService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('refund.RefundService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RefundService(object):
    """Service Message 
    """

    @staticmethod
    def CreateRefund(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/refund.RefundService/CreateRefund',
            refund__pb2.RefundRequest.SerializeToString,
            refund__pb2.RefundResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
